type Event {
  result: String
}

type Todo {

  task: String
  done: Boolean
}

type Query {
  getTodos: [Todo]
}

input TodoInput {
  
  task: String
  done: Boolean
}

type Mutation {
  addTodo(todo: TodoInput): Event
  deleteTodo(id: String): Event
}